spring:
  datasource:
    password: password
    url: jdbc:sqlserver://localhost:1433;databaseName=Shopping
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: YOUR_GOOGLE_CLIENT_ID
          clientSecret: YOUR_GOOGLE_CLIENT_SECRET
          scope:
           - email
           - profile