// <auto-generated />
namespace SV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTbale_monhocLop_sinhvienLop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTbale_monhocLop_sinhvienLop));
        
        string IMigrationMetadata.Id
        {
            get { return "202207272213331_addTbale_monhocLop_sinhvienLop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
